# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bits of wood and bits of strings
email: bowabos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog covering QubesOS, personnal IT security, providing services from your server to your home devices, with a very strong focus on security.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adubois.github.io" # the base hostname & protocol for your site
twitter_username: alexdubois73
github_username:  adubois

# Build settings
markdown: kramdown

theme: jekyll-theme-slate